from AvgWord2VecMapper import AvgWord2VecMapper
from HashingMapper import HashingMapper
from LengthCountMapper import LengthCountMapper
from NgramMapper import NgramMapper
from ParseNumbersMapper import ParseNumbersMapper
from SkipMapper import SkipMapper